### ISSUE TITLE
yi

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-to-cost-function#3]
above you are using yi to refer to the actual y

> And RSS takes the difference between  mxi+b, the  yi value our regression line predicts, and our actual  y, represented by the length of the red lines.

perhaps it would be better to say:

> the y_hat value our regression line predicts, and our actual y

or even

> the y_hat value our regression line predicts, and our actual yi

**Comment by mas16** [comment]
Thanks annieeby! This has been corrected
