### ISSUE TITLE
δ --> d ?

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-to-cost-function#5]
Now using the chain rule to find the partial derivative with respect to a change in the slope, gives us:

dJdmJ(g)=dJdgJ(g(m,b))∗dgdmg(m,b)
dJdmJ(g)=dJdgJ(g(m,b))∗dgdmg(m,b)

could you explain why we go from δ to d here?

**Comment by mas16** [comment]
Thanks annieeby! The symbols have been standardized.
