### ISSUE TITLE
-y or y-

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-to-cost-function#6]
![screen shot 2018-10-31 at 3 39 19 pm](https://user-images.githubusercontent.com/13418713/47817267-38b85b00-dd23-11e8-807d-a36d315bb861.png)
![screen shot 2018-10-31 at 3 39 30 pm](https://user-images.githubusercontent.com/13418713/47817268-38b85b00-dd23-11e8-8f59-5eb2e8a64473.png)

**Comment by mas16** [comment]
Thanks annieeby! This has been corrected.
